Common\Bundle\EntitiesBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
    oneToMany:
        settings:
            targetEntity: Setting
            mappedBy: creator
    lifecycleCallbacks: {  }
